### PR TITLE
Update INSTALL

### PR DESCRIPTION
**Pull request by etam**
fix openSUSE package url

### CODE REVIEW

**Comment by etam** [comment]
(github editor seems to have added newline at the end of file)

**Comment by mackyle** [comment]
So here's a cleaned up version of the URL:

   <https://software.opensuse.org/download.html?project=devel:tools:scm&package=topgit>

BUT the version(s) offered on that page are really outdated (anything
that still installs a `leaves.awk` file is really old in terms of
features, functionality and speed).

Unless you know of a more up-to-date link?, I'm inclined to just remove that line entirely.  It's simple enough to install TopGit by cloning the repo and using `make install` especially since
only a POSIX make etc. is required now.

**Comment by etam** [comment]
I cleaned up the url and reverted the EOL at EOF change.
My request on openSUSE Build Service was also accepted, so it's the latest version there now.

**Comment by mackyle** [comment]
Looks good except for a missing SOB line if you could please add one then I can take the commit as-is.

FYI, looking at:

   <https://build.opensuse.org/package/show/devel:tools:scm/topgit>

I see two failures and one blockage but the older package is available for both of the fails as well as the blocked (which it probably shouldn't be if the block reason is accurate).

**Comment by etam** [comment]
what's "SOB line"?

**Comment by mackyle** [comment]
Take a look at:

   <https://github.com/git/git/blob/master/Documentation/SubmittingPatches#L294>

While it's true this is only a one-line change and just to text at that, without an SOB line I'll end up committing the change myself while giving you credit for reporting it.  But if you include an SOB line in your patch I'll just go ahead and take it with you as the author.

**Comment by etam** [comment]
done

**Comment by mackyle** [comment]
applied and pushed.  thanks.

**Pull request closed without merging**
